var lienzo = document.getElementById("grupb");
        var context = lienzo.getContext("2d");

        context.fillStyle = "White"
        context.fillRect (0,0,800,400);
        context.fillStyle = "#1f0cad";
        context.fillRect(0, 0, 400, 217);
        context.fillStyle = "#e62e2e";
        context.fillRect(400,0, 400, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(400,62, 400, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(400,124, 400, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(400,186, 400, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(0,248, 800, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(0,310, 800, 31);
        context.fillStyle = "#e62e2e";
        context.fillRect(0,372, 800, 31);
        
        
var rc = document.getElementById("GrupB");
      var cr = rc.getContext("2d");


      cr.fillStyle = "White"
      cr.fillRect (0,0,800,200);

      cr.fillStyle = "#35a302"
      cr.fillRect (0,200,800,400)

var gb = document.getElementById("GRUPB");
     var gn = gb.getContext("2d");

     gn.fillStyle = "White"
     gn.fillRect (0,0,800,400);

     gn.fillStyle = "#277502"
     gn.fillRect (0,0,800,140);

     gn.fillStyle = "#e80202"
     gn.fillRect(0,270,800,133)


var mb = document.getElementById("GRUPb");
     var  bm = mb.getContext("2d");
     
     bm.fillStyle = "White"
     bm.fillRect(0,0,800,400);

     bm.fillStyle = "#db1f1f"
     bm.fillRect(0,150,800,100)

     bm.fillStyle = "#db1f1f"
     bm.fillRect(350,0,100,400)
     


